# Assumes backend layers, JAR and dockerfile have been created, see README.md

services:
  reverse-proxy:
    image: nginx:1.23.3-alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
     - frontend
     - backend
  frontend:
    image: mtuomiko/citybikeapp-frontend
    build:
      context: . # code generation needs access to backend API spec file so using root context
      dockerfile: docker/Dockerfile.frontend
    depends_on:
     - backend
  backend:
    image: mtuomiko/citybikeapp-backend
    build:
      context: ./citybikeapp-backend/build/docker/main/
      dockerfile: Dockerfile
    environment:
      DATABASE_CONNECTION_URL: jdbc:postgresql://db:5432/citybikeapp
      DATABASE_CONNECTION_USERNAME: postgres
      DATABASE_CONNECTION_PASSWORD: Hunter2
    depends_on:
     - db
  dataloader:
    image: mtuomiko/citybikeapp-backend
    environment:
      DATABASE_CONNECTION_URL: jdbc:postgresql://db:5432/citybikeapp
      DATABASE_CONNECTION_USERNAME: postgres
      DATABASE_CONNECTION_PASSWORD: Hunter2
    command: dataloader
    depends_on:
     - backend
     - db
    profiles:
     - dataloader
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hunter2
      POSTGRES_DB: citybikeapp
