CREATE TABLE station (
    id              integer          PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name_finnish    text             NOT NULL,
    name_swedish    text             NOT NULL,
    name_english    text             NOT NULL,
    address_finnish text             NOT NULL,
    address_swedish text             NOT NULL,
    city_finnish    text             NOT NULL,
    city_swedish    text             NOT NULL,
    operator        text             NOT NULL,
    capacity        smallint         NOT NULL,
    longitude       double precision NOT NULL,
    latitude        double precision NOT NULL,
    modified_at     timestamptz      NOT NULL,
    created_at      timestamptz      NOT NULL
);

CREATE TABLE journey (
    id                   bigint      PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    departure_at         timestamptz NOT NULL,
    return_at            timestamptz NOT NULL,
    departure_station_id integer     NOT NULL REFERENCES station,
    return_station_id    integer     NOT NULL REFERENCES station,
    distance             integer     NOT NULL,
    duration             integer     NOT NULL
);

ALTER TABLE journey ADD CONSTRAINT journey_content_unique UNIQUE (
    departure_at, return_at, departure_station_id, return_station_id, distance, duration
)
