CREATE TABLE station (
    id              integer          PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name_finnish    text             NOT NULL,
    name_swedish    text             NOT NULL,
    name_english    text             NOT NULL,
    address_finnish text             NOT NULL,
    address_swedish text             NOT NULL,
    city_finnish    text             NOT NULL,
    city_swedish    text             NOT NULL,
    operator        text             NOT NULL,
    capacity        smallint         NOT NULL,
    longitude       double precision NOT NULL,
    latitude        double precision NOT NULL,
    modified_at     timestamptz      NOT NULL,
    created_at      timestamptz      NOT NULL
);

CREATE TABLE journey (
    id                   bigint      PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    departure_at         timestamptz NOT NULL,
    arrival_at           timestamptz NOT NULL,
    departure_station_id integer     NOT NULL REFERENCES station,
    arrival_station_id   integer     NOT NULL REFERENCES station,
    distance             integer     NOT NULL,
    duration             integer     NOT NULL
);

ALTER TABLE journey ADD CONSTRAINT journey_content_unique UNIQUE (
    departure_at, arrival_at, departure_station_id, arrival_station_id, distance, duration
);

CREATE INDEX journey_departure_station_id_idx ON journey (departure_station_id);
CREATE INDEX journey_arrival_station_id_idx ON journey (arrival_station_id);
