logger:
  levels:
#    com:
#      mtuomiko:
#        citybikeapp: DEBUG
#    io:
#      micronaut: DEBUG
#        data: DEBUG
#    org:
#      jdbi: DEBUG
#      stringtemplate: DEBUG
#    org:
#      jooq:
#        tools: DEBUG
#          LoggerListener: DEBUG
