openapi: 3.0.1
info:
  title: City Bike App API
  version: 0.0.3
paths:
  /health:
    get:
      operationId: getHealth
      responses:
        "200":
          description: getHealth 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HealthResult'
  /health/{selector}:
    get:
      operationId: getHealth_1
      parameters:
      - name: selector
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/HealthCheckType'
      responses:
        "200":
          description: getHealth_1 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HealthResult'
  /station/{id}:
    get:
      tags:
      - station
      summary: Get single station information with statistics
      description: Single station information including journey statistics. Statistics
        are filtered using the optional query parameters.
      operationId: getStationWithStatistics
      parameters:
      - name: id
        in: path
        description: Station ID
        required: true
        schema:
          type: integer
          format: int32
      - name: from
        in: query
        description: Earliest journey time to include in station statistics
        schema:
          type: string
          format: date-time
          nullable: true
      - name: to
        in: query
        description: Latest journey time to include in station statistics
        schema:
          type: string
          format: date-time
          nullable: true
      responses:
        "200":
          description: getStationWithStatistics 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StationWithStatistics'
components:
  schemas:
    HealthCheckType:
      type: string
      enum:
      - LIVENESS
      - READINESS
    HealthResult:
      type: object
      properties:
        name:
          type: string
        status:
          $ref: '#/components/schemas/HealthStatus'
        details:
          $ref: '#/components/schemas/Object'
    HealthStatus:
      required:
      - description
      - name
      - operational
      - severity
      type: object
      properties:
        name:
          type: string
        description:
          type: string
          nullable: true
        operational:
          type: boolean
          nullable: true
        severity:
          type: integer
          format: int32
          nullable: true
    Object:
      type: object
    StationStatistics:
      required:
      - arrivalCount
      - arrivalJourneyAverageDistance
      - departureCount
      - departureJourneyAverageDistance
      - topStationsWhereJourneysArriveFrom
      - topStationsWhereJourneysDepartTo
      type: object
      properties:
        departureCount:
          type: integer
          format: int64
        arrivalCount:
          type: integer
          format: int64
        departureJourneyAverageDistance:
          type: number
          format: double
        arrivalJourneyAverageDistance:
          type: number
          format: double
        topStationsWhereJourneysArriveFrom:
          type: array
          items:
            $ref: '#/components/schemas/TopStation'
        topStationsWhereJourneysDepartTo:
          type: array
          items:
            $ref: '#/components/schemas/TopStation'
    StationWithStatistics:
      required:
      - addressFinnish
      - addressSwedish
      - capacity
      - cityFinnish
      - citySwedish
      - id
      - latitude
      - longitude
      - nameEnglish
      - nameFinnish
      - nameSwedish
      - operator
      - statistics
      type: object
      properties:
        id:
          type: integer
          format: int32
        nameFinnish:
          type: string
        nameSwedish:
          type: string
        nameEnglish:
          type: string
        addressFinnish:
          type: string
        addressSwedish:
          type: string
        cityFinnish:
          type: string
        citySwedish:
          type: string
        operator:
          type: string
        capacity:
          type: integer
          format: int32
        longitude:
          type: number
          format: double
        latitude:
          type: number
          format: double
        statistics:
          $ref: '#/components/schemas/StationStatistics'
    TopStation:
      required:
      - id
      - journeyCount
      - nameEnglish
      - nameFinnish
      - nameSwedish
      type: object
      properties:
        id:
          type: integer
          format: int32
        nameFinnish:
          type: string
        nameSwedish:
          type: string
        nameEnglish:
          type: string
        journeyCount:
          type: integer
          format: int64
