name: Backend main pipeline

on:
  push:
    paths: ['citybikeapp-backend/**']
    branches: [master]
  pull_request:
    paths: ['citybikeapp-backend/**']
    branches: [master]
    types: [opened, synchronize]

jobs:
  backend_check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: citybikeapp-backend
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      # use caching for Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: citybikeapp-backend
      # will run test & check tasks also
      - name: Gradle build
        run: ./gradlew clean build jacocoTestCoverageVerification # feeble attempt to keep coverage ratio up
