name: Main verification pipeline

on:
  push:
    paths-ignore: ['docker/**']
    branches: [master]
  pull_request:
    paths-ignore: ['docker/**']
    branches: [master]
    types: [opened, synchronize]

jobs:
  verification:
    runs-on: ubuntu-latest
    env:
      DATABASE_CONNECTION_URL: jdbc:postgresql://localhost:5432/citybikeapp
      DATABASE_CONNECTION_USERNAME: postgres
      DATABASE_CONNECTION_PASSWORD: Hunter2
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: ${{ env.DATABASE_CONNECTION_PASSWORD }}
          POSTGRES_DB: citybikeapp
          PGUSER: postgres # health check uses machine OS user otherwise
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      # Frontend first since it (potentially) fails faster

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: "Frontend: install, generate, lint, build"
        working-directory: citybikeapp-frontend
        run: |
          npm ci 
          npm run client-gen
          npm run lint
          npm run build
      
      # Backend

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle # use caching for Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle build # will run test & check tasks also
        working-directory: citybikeapp-backend
        run: ./gradlew clean build jacocoTestCoverageVerification # feeble attempt to keep test coverage up

      # E2E

      - name: Copy E2E data to backend temp dir where it can pick up them up
        run: |
          cp ./e2e/backend_data/*.csv ./citybikeapp-backend/temp
      - name: Insert basic E2E test data using dataloader
        working-directory: citybikeapp-backend
        env:
          SPRING_PROFILES_ACTIVE: dataloader
          CITYBIKEAPP_DATALOADER_STATIONURL: 'e2e/stations.csv'
          CITYBIKEAPP_DATALOADER_JOURNEYURLS: 'e2e/journeys.csv'
        run: ./gradlew bootRun
      - name: Start backend in background
        working-directory: citybikeapp-backend
        run: ./gradlew bootRun &
      - name: Start frontend devserver in background
        working-directory: citybikeapp-frontend
        run: npm run start &
      - name: Cypress tests # does cypress install and apparently some caching as well
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:e2e
          working-directory: e2e
          wait-on: 'http://localhost:3003, http://localhost:8080/actuator/health'
